---
- name: Install nginx
  yum: name=nginx state=present

- name: Install python-passlib to use htpasswd module
  yum: name=python-passlib state=present

- name: Create SSL key directory
  file:
    path: /etc/ssl/private
    state: directory
    mode: 0700

- name: Generate self-signed key and certificate pair with OpenSSL
  command: openssl req -x509 -nodes -subj "/C=US/ST=Illinois/L=Hell/O=IT/CN=hauptj.com" -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt

- name: Generate dhparam
  command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
  notify: restart nginx

- name: Generate password file for wp-admin directory
  htpasswd:
    path: /etc/nginx/conf.d/.htpasswd
    name: "{{ htpasswd_user }}"
    password: "{{ htpasswd_pass }}"
    crypt_scheme: md5_crypt

- name: Copy nginx configuration for wordpress
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: insert firewalld rule for nginx
  firewalld: port={{ nginx_port }}/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes

- name: http service state
  service: name=nginx state=started enabled=yes
