---
- name: Install nginx
  yum: name=nginx state=present
  
- name: Create SSL key directory
  file:
    path: /etc/ssl/private
    state: directory
    mode: 0700

- name: Generate self-signed key and certificate pair with OpenSSL
  command: openssl req -x509 -nodes -subj "/C=US/ST=Illinois/L=Hell/O=IT/CN=hauptj.com" -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt
  
- name: Generate dhparam
  command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
  notify: restart nginx

- name: Copy nginx configuration for wordpress
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: insert firewalld rule for nginx
  firewalld: port={{ nginx_port }}/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes
  
  # Temporarily disable SELinux to allow NGINX to start
#- name: Temporarily disable SELinux
#  command: setenforce 0

- name: http service state
  service: name=nginx state=started enabled=yes
