---
  # Security Enhanced Linux configuration

- name: Enable selinux
  selinux:
    policy: targeted
    state: enforcing
  when: sel_disable == false

  # necessary?
- name: install selinux-policy-targeted
  yum: name=selinux-policy-targeted state=present
  when: sel_disable == false

- name: install SEManage
  yum: pkg=policycoreutils-python state=present
  when: sel_disable == false

- name: Disable SELinux
  selinux:
    state: disabled
  when: sel_disable == true

- include_tasks: restart.yml
