---
sudo: required
dist: trusty

language: python
python: "2.7"

# Doc: https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix
env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.4.2.0
  - ANSIBLE_VERSION=2.4.1.0
  - ANSIBLE_VERSION=2.4.0.0

before_install:
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

script:
  # syntax check
  - ansible-playbook dns.yml --syntax-check
  - ansible-playbook site.yml --syntax-check

  # dry run - does not work
  #- ansible-playbook dns.yml --check
  #- ansible-playbook site.yml --check
