---
sudo: required

language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

script:
  # check syntax
  - ansible-playbook site.yml -i "hosts" --syntax-check
  # check before install
  #- ansible-playbook site.yml -i "hosts" --check
  # install
  #- ansible-playbook site.yml -i "hosts"
