---
- name: Install WordPress, Redis, MariaDB, Nginx, and PHP-FPM
  hosts: wordpress
  strategy: debug
  #remote_user: root
  remote_user: centos
  become: yes

  pre_tasks:

    - include_role:
        name: ipv6
      become: yes
      become_method: sudo
      become_user: root
      when: ipv6_setup == true

  roles:
    - common
    - selinux
    - fail2ban
    - mariadb
    - nginx
    - php-fpm
    - wordpress
    - redis
