---
- name: Install Fail2ban, WordPress, Redis, MariaDB, Nginx, and PHP-FPM
  hosts: wp-dev
  strategy: debug
  remote_user: centos
  become: yes


  roles:
    #- { role: ipv6, when: ipv6_setup == true, become: yes, become_method: sudo, become_user: root }
    - repos
    #- { role: updates, when: auto_updates == true }
    - selinux
    #- fail2ban
    #- mariadb
    - nginx
    - php-fpm
    #- wordpress
    - redis
