---
- name: Install WordPress, Redis, MariaDB, Nginx, and PHP-FPM
  hosts: wp-dev
  strategy: debug
  remote_user: centos
  become: yes


  roles:
    - { role: ipv6, when: ipv6_setup == true, become: yes, become_method: sudo, become_user: root }
    - common
    - selinux
    - { role: fail2ban, when: firewall_serv == "fail2ban" or firewall_serv == "firewalld" }
    - { role: csf-ansible-role, when: firewall_serv == "csf" or firewall_serv == "CSF" }
    - mariadb
    - nginx
    - php-fpm
    - wordpress
    - redis
